name: Label and Issue Workflow
on:
  label:
    types: [created]
  issues:
    types: [opened]

jobs:
  print_event_details:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger - ${{ github.event_name }}, user - ${{ github.actor }}, date - `date`"
